image: Visual Studio 2019

install:
  - ps: gitversion /l console /output buildserver

configuration:
  - Release

dotnet_csproj:
  patch: true
  version: '$(GitVersion_SemVer)'

build_script:
  - cmd: dotnet build
  - cmd: dotnet pack

test: off

artifacts:
  - path: '**\*.nupkg'